adding changes to srgan module to reflect new leto structure
DISHDevEx/leto pull request #2
Opened 2023-07-18 08:01 UTC by vinayakSharm

Creating 2 Modules

Reduction Module using ffmpeg. 
Can be run using python file: leto/reduction/ffmpeg_resolution_downsampler/ffmpeg_resolution_downsampler.py

Reconstruction module using RealBasicVSR:
PreProcessing python file: realbasicvsr_preprocessing.py
Inference python file: reconstruction_realbasicvsr.py
PostProcessing python: realbasicvsr_postprocessing.py

--other files to support the creation of the SRGAN(builder.py, reconstruction_setup.sh, realbasicvsr_x4.py)

All files have arg parsing. 

Removes the need for jupyter notebook. Deployable onto infrastructure.

2023-07-18 23:00 UTC, PierceLovesee reviewed
Please change the structure of the README(s)

2023-07-20 17:33 UTC, vinayakSharm commented on README.md
hi pierce. thanks for the suggestion. after some thought I think Its best to keep everything at the root readme to make it easy to run both reduction and reconstruction techniques in pairs. isolated readmes will make it hard to run things in pairs. 

as we grow if the readme becomes too messy we can start to clean it up

2023-07-20 20:03 UTC, ankitadpatil requested changes

2023-07-24 04:36 UTC, ankitadpatil requested changes
Unable to run reconstruction/realbasicvsr/realbasicvsr_postprocessing.py
Encountered following error - 
  File "realbasicvsr_postprocessing.py", line 71, in <module>
    main()
  File "realbasicvsr_postprocessing.py", line 56, in main
    aux.upload_s3(recon_vid_obj, bucket = args.output_bucket_s3, prefix = args.ouput_prefix_s3)
  File "/opt/conda/lib/python3.7/site-packages/aEye/auxiliary.py", line 174, in upload_s3
    s3.upload_file(path, bucket, prefix + video.get_output_title())
............
FileNotFoundError: [Errno 2] No such file or directory: './reconstructed_videos/reconstructed_videos'

2023-07-24 04:36 UTC, ankitadpatil commented on README.md
> +  apt-get update && apt-get install libgl1
This happened because I tried your code in SageMaker Terminal instead of SageMaker Notebook instance. 
The code works fine in SageMaker Notebook.

2023-07-24 04:36 UTC, ankitadpatil commented on reconstruction/realbasicvsr/reconstruction_setup.sh
> +apt-get update && apt-get install libgl1
This happened because I tried your code in SageMaker Terminal instead of SageMaker Notebook instance.
The code works fine in SageMaker Notebook.

2023-07-24 15:14 UTC, vinayakSharm commented on reconstruction/realbasicvsr/realbasicvsr_postprocessing.py
> +        os.remove("./RealBasicVSR_x4.pth")
yes, updated. good catch.

2023-07-24 19:42 UTC, vinayakSharm commented on reconstruction/realbasicvsr/reconstruction_setup.sh
> +apt-get update && apt-get install libgl1
Argument for keeping apt-get: this code will be eventually run on either an ec2 terminal or a docker image running underlying linux. The base image for the time being will have apt-get :)

2023-07-24 19:42 UTC, vinayakSharm commented on README.md
> +cd leto/reconstruction/RealBasicVSR
resolved

2023-07-24 19:42 UTC, vinayakSharm commented on README.md
> +  apt-get update && apt-get install libgl1
Argument for keeping apt-get: this code will be eventually run on either an ec2 terminal or a docker image running underlying linux. The base image for the time being will have apt-get :)

2023-07-24 19:43 UTC, vinayakSharm commented
> Unable to run reconstruction/realbasicvsr/realbasicvsr_postprocessing.py
> Encountered following error -
> File "realbasicvsr_postprocessing.py", line 71, in
> main()
> File "realbasicvsr_postprocessing.py", line 56, in main
> aux.upload_s3(recon_vid_obj, bucket = args.output_bucket_s3, prefix = args.ouput_prefix_s3)
> File "/opt/conda/lib/python3.7/site-packages/aEye/auxiliary.py", line 174, in upload_s3
> s3.upload_file(path, bucket, prefix + video.get_output_title())
> ............
> FileNotFoundError: [Errno 2] No such file or directory: './reconstructed_videos/reconstructed_videos'

resolved :)

2023-07-24 19:52 UTC, vinayakSharm commented on reduction/ffmpeg_resolution_downsampler/ffmpeg_resolution_downsampler.py
> +    Parses the arguments needed for RealBasicVSR reconstruction module.
resolved

2023-07-24 19:52 UTC, vinayakSharm commented on reduction/ffmpeg_resolution_downsampler/ffmpeg_resolution_downsampler.py
> +    Catalogues: config, checkpoint, input dir, output dir, maximum sequence length, and fps
resolved

2023-07-24 20:54 UTC, ankitadpatil reviewed
Just a comment about README. Everything else looks good and works as well. Great job with the code and structure!

2023-07-24 20:54 UTC, ankitadpatil commented on README.md
> +cd ~/leto/reconstruction/realbasicvsr
Can we change this to the following to keep it uniform across reduction and reconstruction? 
cd leto/reconstruction/realbasicvsr

2023-07-24 21:06 UTC, ankitadpatil commented on README.md
> +cd ~/leto/reconstruction/realbasicvsr
It makes sense to keep the original command, as the intent is to go out the reduction folder and into reconstruction folder.

2023-07-24 21:07 UTC, ankitadpatil approved these changes
Approving PR. Great work Vinny!

2023-07-24 21:42 UTC, merged