Luan/cv compression
DISHDevEx/leto pull request #21
Opened 2023-08-03 17:10 UTC by luanlam97

2023-08-03 20:03 UTC, ankitadpatil requested changes
Requested some structural changes.

2023-08-03 20:28 UTC, ankitadpatil requested changes
Please change the name of the folder from cv2_jpg_compression to cv2_jpg_reduction

Please change the name of python file from cv2_jpg_compression to cv2_jpg_reduction.py

2023-08-03 20:28 UTC, ankitadpatil commented on reduction/cv2_jpg_compress/cv2_jpg_compress.py
> +                        default = "reduced-videos/cv2_compression/",
Please change the default value to "reduced-videos/benchmark/cv2_reduction/car/" to keep the file structure consistent in s3.

2023-08-03 20:28 UTC, ankitadpatil commented on reduction/cv2_jpg_compress/cv2_jpg_compress.py
> +def cv2_jpg_compress(video, path = "temp" , quality = 15, crf = 28):
Please use the term reduction instead of compression. I believe we are trying to avoid using compression and decompression so there is no confusion with codecs.

2023-08-03 21:17 UTC, luanlam97 commented on reduction/cv2_jpg_compress/cv2_jpg_compress.py
> +                        default = "reduced-videos/cv2_compression/",
resolved!

2023-08-03 21:17 UTC, luanlam97 commented on reduction/cv2_jpg_compress/cv2_jpg_compress.py
> +def cv2_jpg_compress(video, path = "temp" , quality = 15, crf = 28):
resolved!

2023-08-03 21:50 UTC, luanlam97 commented on reduction/cv2_jpg_compress/requirements_cv2_jpg_compress.txt
> +opencv-python>= 4.8.0.74
yes, you are totally right! I will remove it

2023-08-03 21:56 UTC, luanlam97 commented on reduction/cv2_jpg_compress/cv2_jpg_compress.py
> +def parse_args():
So I asked Vinny and apparently they (Vinny, hamza, and pierce) are discussing the merit of it and such. 
For now, I think I push this pr without it

2023-08-03 22:16 UTC, ankitadpatil requested changes
Requested change.

2023-08-03 22:16 UTC, ankitadpatil commented on reduction/cv2_jpg_reduction/cv2_jpg_reduction.py
> +        cv2_jpg_compress(video, args.temp_path, args.quality, args.crf)
cv2_jpg_reduction(video, args.temp_path, args.quality, args.crf)

2023-08-04 15:25 UTC, ankitadpatil commented on reduction/cv2_jpg_compress/cv2_jpg_compress.py
> +def parse_args():
Resolving this conversation as the team has decided to move forward with current structure of cv2_jpg_reduction.py

2023-08-04 15:25 UTC, luanlam97 commented on reduction/cv2_jpg_reduction/cv2_jpg_reduction.py
> +        cv2_jpg_compress(video, args.temp_path, args.quality, args.crf)
resolved!

2023-08-04 15:28 UTC, ankitadpatil commented on reduction/cv2_jpg_compress/cv2_jpg_compress.py
> +def main():
Resolving this conversation as the team has decided to move forward with current structure of cv2_jpg_reduction.py for now

2023-08-04 15:43 UTC, ankitadpatil requested changes
As we are trying to keep the name of the video same throughout the R1 and R2 process for the ease of generating metrics, requesting few changes to remove 'compressed_' prefix added to the video file name.

2023-08-04 15:43 UTC, ankitadpatil commented on reduction/cv2_jpg_reduction/cv2_jpg_reduction.py
> +    out = cv2.VideoWriter(f"{path}_cv2/compressed_" + title,cv2.VideoWriter_fourcc(*'mp4v'), fps, (frame_width,frame_height))
out = cv2.VideoWriter(f"{path}_cv2/" + title, cv2.VideoWriter_fourcc(*'mp4v'), fps, (frame_width,frame_height))

2023-08-04 15:43 UTC, ankitadpatil commented on reduction/cv2_jpg_reduction/cv2_jpg_reduction.py
> +    cmd = f"static_ffmpeg -y -i {path}_cv2/compressed_{title} -c:v libx264  -crf {crf} -preset slow {path}/compressed_{title}"
cmd = f"static_ffmpeg -y -i {path}_cv2/{title} -c:v libx264  -crf {crf} -preset slow {path}/{title}"

2023-08-04 15:43 UTC, ankitadpatil commented on reduction/cv2_jpg_reduction/cv2_jpg_reduction.py
> +    os.remove(f'{path}_cv2/compressed_{title}')
os.remove(f'{path}_cv2/{title}')

2023-08-04 16:01 UTC, ankitadpatil approved these changes
Everything looks good. Great job!

2023-08-04 17:13 UTC, merged