Pierce/config fix
DISHDevEx/leto pull request #35
Opened 2023-08-16 17:46 UTC by PierceLovesee

This PR implements the following:

- Standardizes S3 output paths for both R1 and R2 methods
- Ability to execute R1/R2 methods from the root Leto directory, or any directory within the Leto for that matter.
- Removes old recon_args argument parsing
- Updates main Readme to give instructions on how to:
    - create a new section in config.ini
    - modify an existing section of config.ini
- Implements minor syntax errors in config.ini

2023-08-16 18:05 UTC, vinayakSharm commented on README.md
love the new section on the readme. 
can we remove the deprecated python commands at the bottom? maybe even remove that section entirely since the config parser allows us to run everything in a homogenous way. 

you could keep the mapping though.

2023-08-16 18:06 UTC, vinayakSharm commented on config.ini
good!

2023-08-16 18:10 UTC, vinayakSharm commented on utilities/config_handler.py
> +from pathlib import Path
add a module docstring at the top

2023-08-16 18:11 UTC, vinayakSharm requested changes
your code in this PR is elegant pierce. im really impressed. initial review looks great. thanks for bringing hygiene to the repo. small edits to the readme. im gonna run the code next to make sure everything looks good.

2023-08-16 20:30 UTC, PierceLovesee commented on README.md
Got that updated.  Sections of the main README are now:

- Using the config.ini
- Making a new method with the config.ini
- Installing requirements
- Project structure

2023-08-16 20:30 UTC, PierceLovesee commented on config.ini
👍

2023-08-16 20:38 UTC, PierceLovesee commented on utilities/config_handler.py
> +from pathlib import Path
Got 'er in there.

2023-08-16 20:58 UTC, ankitadpatil requested changes

2023-08-16 20:58 UTC, ankitadpatil commented on README.md
> +6. Run your .py file.  Boom, no you can dynamically allocate parameters in the ***config.ini*** file and then execute the .py file cleanly without CLI input.
6. Run your .py file.  Boom, **now** you can dynamically allocate parameters in the ***config.ini*** file and then execute the .py file cleanly without CLI input.

2023-08-16 20:58 UTC, ankitadpatil commented on README.md
> +pip install -r <REQUIREMENTS.TXT>
Just a thought! Can we name all the different requirement files in different folders as simply requirements.txt instead of requirements_<method_name>.py? 
That way pip install command stays the same throughout, all you need to do is cd into the appropriate folder, as you mentioned. 

pip install -r requirements.txt

2023-08-16 22:18 UTC, ankitadpatil requested changes

2023-08-16 22:18 UTC, ankitadpatil commented on README.md
>  ```
Can there be a section to mention mapping between reduction and reconstruction techniques?

2023-08-17 21:06 UTC, PierceLovesee commented on README.md
> +6. Run your .py file.  Boom, no you can dynamically allocate parameters in the ***config.ini*** file and then execute the .py file cleanly without CLI input.
changed 'no' to 'now' 👍

2023-08-17 21:07 UTC, PierceLovesee commented on README.md
> +pip install -r <REQUIREMENTS.TXT>
For sure!  I'll change those now.

2023-08-17 21:30 UTC, PierceLovesee commented on README.md
>  ```
👍  got it put in there :)

2023-08-17 21:44 UTC, vinayakSharm approved these changes
looks good!

2023-08-17 22:52 UTC, ankitadpatil requested changes

2023-08-17 22:52 UTC, ankitadpatil commented on README.md
> +output_prefix_s3 = reduced-videos/%(method_name)s-fps_%(fps)s-bitrate_%(bitrate)s/
In lieu of recent changes to config file - 
output_prefix_s3 = reduced-videos/${method_name}-fps_${fps}-bitrate_${bitrate}/

2023-08-17 22:52 UTC, ankitadpatil commented on README.md
> +output_prefix_s3 = reduced-videos/%(method_name)s-fps_%(fps)s-bitrate_%(bitrate)s/
In lieu of recent changes to config file -
output_prefix_s3 = reduced-videos/${method_name}-fps_${fps}-bitrate_${bitrate}/

2023-08-17 22:55 UTC, ankitadpatil requested changes

2023-08-17 22:55 UTC, ankitadpatil commented on README.md
> +bitrate = 0
Did you intend to write 0?

2023-08-18 22:43 UTC, PierceLovesee commented on README.md
> +bitrate = 0
yup!  The underlying aEye code takes that as a default 10x bitrate reduction.

2023-08-18 22:44 UTC, PierceLovesee commented on README.md
> +output_prefix_s3 = reduced-videos/%(method_name)s-fps_%(fps)s-bitrate_%(bitrate)s/
The default interpolation still works when the advanced interpolation is enabled.  I think we should leave this as is, so the interpolation is kept local to the section.

2023-08-18 22:44 UTC, PierceLovesee commented on README.md
> +output_prefix_s3 = reduced-videos/%(method_name)s-fps_%(fps)s-bitrate_%(bitrate)s/
The default interpolation still works when the advanced interpolation is enabled.  I think we should leave this as is, so the interpolation is kept local to the section.

2023-08-21 17:29 UTC, ankitadpatil approved these changes
All the techniques work well. Super neat job with ConfigHandler class and config file. Love the README.

2023-08-21 17:30 UTC, merged