Ankita/reconstruction
DISHDevEx/leto pull request #4
Opened 2023-07-19 05:32 UTC by ankitadpatil

Addition to reconstruction module - 
1. Reconstruction using OpenCV (leto/reconstruction/video_upscaler.py)
2. Reconstruction using Deep Neural Networks Super Resolution (leto/reconstruction/video_superres.py)
Both files use arg parsing; s3 naming conventions and structure according to project Leto's standards 

Addition to runner notebooks - 
1. reconstruction_opencv_superres.ipynb - Illustrates reduction method using aEye modules and reconstruction method using both video_upscaler.py and video_superres.py

Steps to test - 
1. $ python reconstruction/video_upscaler.py
2. $ python reconstruction/video_superres.py
3. Running runner_notebooks/reconstruction_opencv_superres.ipynb

2023-07-21 19:58 UTC, vinayakSharm requested changes
hi ankita. the code looks pretty solid right now. 

only comment would be to remove the jupyter notebook and add the runner instructions to the root readme. 

will be running the code over the weekend and providing feedback if necessary. 

awesome work!

2023-07-24 20:10 UTC, vinayakSharm commented on runner_notebooks/reconstruction_opencv_superres.ipynb
remove this :) add instructions to read me

2023-07-24 20:10 UTC, vinayakSharm commented on reconstruction/superres/requirements_superres.txt
add a version to the aEye module, indication > than for latest version compatability

2023-07-24 20:10 UTC, vinayakSharm commented on reconstruction/opencv_resolution_upscaler/requirements_opencv_resolution_upscaler.txt
add version, and > for latest package release compatibility

2023-07-24 20:11 UTC, vinayakSharm commented on modified/resized_demo_10_second_clip.mp4
no videos in pr pls :)

2023-07-24 20:21 UTC, vinayakSharm commented on reconstruction/superres/.nfsc516183f74a6396f00000001
what is this file? is the binary necessary to keep in github?

2023-07-24 20:24 UTC, vinayakSharm requested changes
once initial changes applied I will start running code :)

2023-07-24 22:48 UTC, ankitadpatil commented on runner_notebooks/reconstruction_opencv_superres.ipynb
removed notebook.

2023-07-24 22:49 UTC, ankitadpatil commented on modified/resized_demo_10_second_clip.mp4
good catch, removed.

2023-07-24 22:50 UTC, ankitadpatil commented on reconstruction/superres/.nfsc516183f74a6396f00000001
I believe that was generated while running reconstruction_superres.py. I have deleted it. Please check if it is recreated after running the python file again.

2023-07-24 22:57 UTC, ankitadpatil commented on reconstruction/superres/requirements_superres.txt
Added aEye's version.

2023-07-24 22:57 UTC, ankitadpatil commented on reconstruction/opencv_resolution_upscaler/requirements_opencv_resolution_upscaler.txt
Added aEye's version.

2023-07-25 16:34 UTC, vinayakSharm commented on reconstruction/opencv_resolution_upscaler/opencv_resolution_upscaler.py
> +    s3_client.download_file(args.input_bucket_s3, args.input_prefix_s3, input_video_path)
can we use aEye Aux class to download videos? will maintain consistency, and reuse the boto3 download functionality that already exists in the aEye module.

2023-07-25 16:46 UTC, vinayakSharm requested changes
needs to implement aEye aux class for video downloading and handling, to reduce the redundancy of instantiation and to create consistency in the code base. 

Asked some stimuli questions that do not need answers for this PR. Just to provoke thought.

2023-07-25 16:46 UTC, vinayakSharm commented on reconstruction/opencv_resolution_upscaler/opencv_resolution_upscaler.py
> +def upscale_video():
stimuli question, not commentary:

what is the main difference between the cv2 functionality presented here, and the ffpmeg change_resolution function from https://github.com/DISHDevEx/aEye/blob/main/aEye/labeler.py.

2023-07-25 16:46 UTC, vinayakSharm commented on reconstruction/opencv_resolution_upscaler/opencv_resolution_upscaler.py
> +            resized_frame = cv2.resize(frame,args.scaling_resolution,fx=0,fy=0, interpolation = cv2.INTER_CUBIC)
I like that you are using inter cubic. 

however, question: if we are downsampling with lanczos, (from https://github.com/DISHDevEx/aEye/blob/main/aEye/labeler.py, change_resolution function), how does upsampling with a different technique impact the video. 

Should downsampling with lanczos be paired with upsampling with lanczos? or does a mix of techniques create better videos?

(this is partially rhetorical :) because we will have to benchmark the videos and find out!!)

2023-07-25 16:46 UTC, vinayakSharm commented on reconstruction/superres/reconstruction_superres.py
> +    model = s3_client.download_file(Bucket = args.model_bucket_s3, Key = args.model_prefix_s3, Filename = model_path)
in a future sprint, we should create some model download utilities to reduce the redundancy of downloading models. Both RealBasicVSR, and superres download files from S3. 

We should mark this as tech debt that you, I , or tamanna can tackle later :)

2023-07-25 16:46 UTC, vinayakSharm commented on reconstruction/superres/reconstruction_superres.py
> +        s3_client.put_object(Body=file, Bucket=args.output_bucket_s3, Key=args.output_prefix_s3)
can we use aEye aux functionality to put videos back to s3?

2023-07-25 16:46 UTC, vinayakSharm commented on reconstruction/superres/reconstruction_superres.py
this is such a beautiful model. and the code is very elegant.

2023-07-25 17:15 UTC, vinayakSharm requested changes

2023-07-25 17:15 UTC, vinayakSharm commented on reconstruction/superres/reconstruction_superres.py
we need to separate out the cloud functionality from the model functionality. The model should be agnostic of the cloud implementation. 

A couple ways you could do this. 

you can make separate out the runner workflow and model workflow into two seperate functions. and run them both in main. 

you could separate out the steps into different files (preprocess, model implementation, post process)

or you could create some classes and run functions from that.

2023-07-25 17:15 UTC, vinayakSharm commented on reconstruction/opencv_resolution_upscaler/opencv_resolution_upscaler.py
> +def upscale_video():
can we please separate out the cloud functionality from the cv2 upscaler functionality. 

this can be as simple as making separate functions for the cloud implementations, and only run the core cv2 upsampling in the def upscale video. 

you could also see if the upscale video fits in the extractor class in aEye. 

or even separate out multiple files into steps. 

any solution is acceptable, I think moving forward we will have to make the repo more OOP, but that can be done in later sprints.

2023-07-25 17:15 UTC, vinayakSharm commented on reconstruction/superres/reconstruction_superres.py
I think moving forward we will have to make the repo more OOP, but that can be done in later sprints.

2023-07-25 17:20 UTC, vinayakSharm commented
Reasoning for seperating out cloud functionality:

For our research and dev purposes we are assuming all items live in S3. 

But this repo should be flexible enough to adapt as we move forward with any implementation that live view prefers, and it will make it easier for us to adapt constantly to many different use cases of video bit rate reduction in the future.

2023-07-25 23:05 UTC, ankitadpatil commented on reconstruction/opencv_resolution_upscaler/opencv_resolution_upscaler.py
> +    s3_client.download_file(args.input_bucket_s3, args.input_prefix_s3, input_video_path)
Removed above line of code and added Aux's load_s3 function. Edited remaining code that processes list of videos instead of a single video.

2023-07-25 23:09 UTC, ankitadpatil commented on reconstruction/opencv_resolution_upscaler/opencv_resolution_upscaler.py
> +            resized_frame = cv2.resize(frame,args.scaling_resolution,fx=0,fy=0, interpolation = cv2.INTER_CUBIC)
The interpolation should have been lancozs instead of inter_cubic. Thanks for catching that! 
I believe sticking to the same technique while downsampling and upsampling might make the process more efficient.

2023-07-25 23:10 UTC, ankitadpatil commented on reconstruction/superres/reconstruction_superres.py
> +    model = s3_client.download_file(Bucket = args.model_bucket_s3, Key = args.model_prefix_s3, Filename = model_path)
I picked this line of code from your download_model function from builder.py
The function may have a potential to be in utilities instead of being tucked away in reconstruction/realbasicvsr/builder.py

2023-07-26 18:21 UTC, ankitadpatil commented on reconstruction/superres/reconstruction_superres.py
> +        s3_client.put_object(Body=file, Bucket=args.output_bucket_s3, Key=args.output_prefix_s3)
Updated code base to use aEye functionality.

2023-07-26 18:22 UTC, ankitadpatil commented on reconstruction/superres/reconstruction_superres.py
Thank you!

2023-07-26 18:25 UTC, ankitadpatil commented on reconstruction/opencv_resolution_upscaler/opencv_resolution_upscaler.py
> +def upscale_video():
Updated code. Let me know if it changes are needed.

2023-07-26 18:26 UTC, ankitadpatil commented on reconstruction/superres/reconstruction_superres.py
Updated the code base for now, but open to more feedback in this direction.

2023-07-27 16:15 UTC, vinayakSharm approved these changes
looks good for a v0 runs great.

2023-07-27 17:42 UTC, merged