Monisha/background subtraction
DISHDevEx/leto pull request #44
Opened 2023-08-23 16:53 UTC by mg6955

Background addition module with cloud functionality and config.ini changes

2023-08-24 17:42 UTC, vinayakSharm commented on reduction/background_subtraction/background_subtractor.py
hi monisha can you remove the background subtraction files from this PR as they will be tested in tamanna's background subtraction PR

2023-08-24 17:42 UTC, vinayakSharm commented on reconstruction/backgroundaddition/requirements_background_addition.txt
hi monisha can you remove the background subtraction files from this PR as they will be tested in tamanna's background subtraction PR

2023-08-24 17:49 UTC, vinayakSharm requested changes
looks good. 

few docstring concerns. 

can you auto format with black? some of the spacing is odd. 


only real concern is why the fps of the output video is hardcoded? is this intentional, would you like to have the video output in different fps? :)

2023-08-24 17:49 UTC, vinayakSharm commented on reconstruction/backgroundaddition/background_addition.py
> +      """
pls fix docstring alignment

2023-08-24 17:49 UTC, vinayakSharm commented on reconstruction/backgroundaddition/background_addition.py
> +    """This methods adds static background to masked image
pls fix formatting for docstring

2023-08-24 17:49 UTC, vinayakSharm commented on reconstruction/backgroundaddition/background_addition.py
> +    Videopath: path to image
docstring variable names do not match the actual variable names

2023-08-24 20:57 UTC, mg6955 commented on reduction/background_subtraction/background_subtractor.py
Okay!

2023-08-25 14:28 UTC, mg6955 commented on reconstruction/backgroundaddition/background_addition.py
> +    out = cv2.VideoWriter(output_path, fourcc, 30, (frame_width, frame_height))
I thought the videos we encode has a constant fps of 30s. Should I encode it to the fps of input video?

2023-08-25 15:04 UTC, mg6955 commented on reconstruction/backgroundaddition/background_addition.py
> +    Videopath: path to image
Fixed

2023-08-25 15:04 UTC, mg6955 commented on reconstruction/backgroundaddition/background_addition.py
> +    """This methods adds static background to masked image
Fixed

2023-08-25 15:04 UTC, mg6955 commented on reconstruction/backgroundaddition/background_addition.py
> +      """
Fixed

2023-08-25 15:04 UTC, mg6955 commented on reduction/background_subtraction/requirements_background_subtraction.txt
Removed

2023-08-25 21:24 UTC, vinayakSharm commented on config.ini
> +output_prefix_s3 = reconstructed-videos/%(method_name)s/
hi monisha this needs to be a $ sign instead of % sign

2023-08-25 21:39 UTC, vinayakSharm approved these changes

2023-08-25 21:44 UTC, merged