Tamanna/reduction keyframe extraction
DISHDevEx/leto pull request #54
Opened 2023-08-29 20:08 UTC by tamannak8

Adding keyframe extraction PR

2023-09-01 20:15 UTC, vinayakSharm commented on reduction/keyframe_extraction/keyframe_extraction.py
> +        Parameters:
ca you add the "------" underneath

2023-09-01 20:15 UTC, vinayakSharm commented on reduction/keyframe_extraction/keyframe_extraction.py
> +    Args:
Parameters

2023-09-01 20:31 UTC, vinayakSharm reviewed
small docstring change, but looks good! good job

2023-09-05 23:28 UTC, ankitadpatil requested changes

2023-09-05 23:28 UTC, ankitadpatil commented on reduction/keyframe_extraction/keyframe_extraction.py
> +import boto3
Unused import boto3

2023-09-05 23:28 UTC, ankitadpatil commented on reduction/keyframe_extraction/keyframe_extraction.py
> +        frame_count = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
Unused variable frame_count

2023-09-05 23:28 UTC, ankitadpatil commented on reduction/keyframe_extraction/keyframe_extraction.py
> +        frame_rate = cap.get(cv2.CAP_PROP_FPS)
Unused variable frame_rate

2023-09-05 23:28 UTC, ankitadpatil commented on reduction/keyframe_extraction/keyframe_extraction.py
> +        # duration_seconds = frame_count / frame_rate
Please delete this line

2023-09-14 16:29 UTC, ankitadpatil requested changes

2023-09-14 16:29 UTC, ankitadpatil commented on reduction/keyframe_extraction/keyframe_extraction.py
> +
The change has been added by @tamannak8

2023-09-14 16:30 UTC, ankitadpatil approved these changes
Everything looks and works well. Great job with the code for keyframe extraction technique!

2023-09-14 20:43 UTC, merged