Tamanna/linear interpolation
DISHDevEx/leto pull request #56
Opened 2023-08-30 05:12 UTC by tamannak8

Linear interpolation of keyframes

2023-09-01 19:23 UTC, vinayakSharm commented on reconstruction/linear_interpolator/linear_interpolator.py
> +def reconstruct_video_with_keyframe_images(target_frame_rate=30):
docstrings pls

2023-09-01 19:23 UTC, vinayakSharm commented on reconstruction/linear_interpolator/linear_interpolator.py
> +def linear_interpolation(frame_a, frame_b, alpha):
docstring

2023-09-01 19:23 UTC, vinayakSharm commented on reconstruction/linear_interpolator/linear_interpolator.py
> +import cv2
module docstring

2023-09-01 19:41 UTC, vinayakSharm commented on reconstruction/linear_interpolator/linear_interpolator.py
> +        num_interpolated_frames = int((target_frame_rate / frame_rate) - 1)
can you rename this variable its misleading. Its not the number of interpolated frames. Its actually the the number of interpolated frames per second.

2023-09-01 19:46 UTC, vinayakSharm commented on reconstruction/linear_interpolator/linear_interpolator.py
> +        num_interpolated_frames = int((target_frame_rate / frame_rate) - 1)
more over, its a factor. So this difference og_fps, and the requested_fps allows you to determine the factor multiple by which to create frames

2023-09-01 20:03 UTC, vinayakSharm requested changes
hi tamanna small docstring request. 

also could you help me understand the algorithm irl :)

2023-09-06 16:11 UTC, tamannak8 commented on reconstruction/linear_interpolator/linear_interpolator.py
> +        num_interpolated_frames = int((target_frame_rate / frame_rate) - 1)
updated

2023-09-15 06:42 UTC, vinayakSharm commented on reconstruction/linear_interpolator/linear_interpolator.py
> +    - target_frame_rate: The desired frame rate for the reconstructed video (default is 30).
hi tamanna no "-" to create consistency in code base.

2023-09-15 06:45 UTC, vinayakSharm commented on reconstruction/linear_interpolator/linear_interpolator.py
> +                out.write(interpolated_frame)
hi tamanna in the while loop my worry is that we are not writing frame_a and frame_b. Only the interpolated frame. Shouldn't we be writing all 3?

2023-09-15 06:48 UTC, vinayakSharm requested changes
Small change on the "-" in the docstring. 

Comment/concern on writing out only the interpolated frames and not frames a,b in for loop. (google chatted as well :) )

2023-09-18 15:13 UTC, tamannak8 commented on reconstruction/linear_interpolator/linear_interpolator.py
> +                out.write(interpolated_frame)
if alpha is 0 then it automatically writes frame a and when alpha =1 it writes frame b
so it gets handled
if you see add weighted formula it alpha*frame b and (1- alpha)*framea

2023-09-18 15:36 UTC, vinayakSharm commented on config.ini
> +=======
hi tamanna it seems as though from merging main into your branch there is still an unresolved merge conflict:

"<<<<<<< HEAD
invocation_type = RequestResponse ; Use 'Event' for asynchronous invocation
=======
invocation_type = RequestResponse ; Use 'Event' for asynchronous invocation
=======
invocation_type = RequestResponse ; Use 'Event' for asynchronous invocation
"

please clear this out :)

2023-09-18 15:41 UTC, vinayakSharm commented on reconstruction/linear_interpolator/linear_interpolator.py
> +    frame_a: The first input image frame (numpy.ndarray).
the docstrings are really close. 

they need an indent, and the type list afer the colon, with the description underneath

ex/ from superres
      
          Parameters
          ----------
              model_prefix_s3: string
                  the prefix of the pretrained model as stored in s3.
      
          Returns
          ----------
              split_on_scaling: string
                  defines which model to use for cv2.dnn_superres as parsed from the model_prefix_s3

could you please fix them for this python file.

2023-09-18 15:43 UTC, vinayakSharm requested changes
hi tamanna the logic for the linear interpolation has been cleared. Thanks for helping me out on friday to understand this. 

there are 2 things. I just caught a bug in your config.ini 

and the docstrings have been formatted with the "----" however they still need to be modified to achieve consistency with the rest of the code base

2023-09-18 16:52 UTC, vinayakSharm approved these changes
thanks!

2023-09-18 16:57 UTC, merged