adding metadata lambda function to repository for version control
DISHDevEx/leto pull request #60
Opened 2023-08-31 05:53 UTC by PierceLovesee

Lambda function for extracting metadata from all videos in a directory on S3 and writing specified metadata fields (right now, fps and bitrate) to dynamoDB.

Depends on execution from invoke_lambda_async.py.

2023-09-01 15:27 UTC, vinayakSharm commented on benchmarking/video_quality/lambda_metadata.py
> +import subprocess
module docstring

2023-09-01 15:29 UTC, vinayakSharm commented on benchmarking/video_quality/lambda_metadata.py
> +    Args:
add the " -------" underneath the args and returns for standardized format

2023-09-01 15:31 UTC, vinayakSharm commented on benchmarking/video_quality/lambda_metadata.py
> +        local_filename = "/tmp/" + os.path.basename(key)
nice --> like the .basename

2023-09-01 15:33 UTC, vinayakSharm commented on benchmarking/video_quality/lambda_metadata.py
> +    Args:
docstring stuff : "-----" underneath the args and returns

2023-09-01 15:34 UTC, vinayakSharm requested changes
small docstring updates. 

question on the validity of list_object_keys if video not in mp4 encoding?

2023-09-05 20:56 UTC, hamzakhokhar approved these changes

2023-09-05 21:07 UTC, vinayakSharm approved these changes
good.

2023-09-05 21:14 UTC, merged